# 设置
setting:
  # 选择语言
  lang: "zh_CN"

# 数据存储
data:
  # 存储类型 YAML MYSQL
  type: YAML
  mysql:
    # 数据库设置
    host: localhost
    port: 3306
    user: root
    password: password
    database: questengine
    table: quest_engine